- app/services/api_maker/models_generator_service.rb
- lib/api_maker/javascript/BaseModel.js.erb
- lib/api_maker/javascript/ModelName.js.erb
- lib/api_maker/javascript/ModelTemplate.js.erb
Asana: https://app.asana.com/0/768645078183109/821792448045096
> Added support for modal name

- lib/api_maker/memory_storage.rb
Asana: https://app.asana.com/0/741415267509551/884019815268829
> Fixed double generated methods

- lib/api_maker/preloader_belongs_to.rb
- lib/api_maker/preloader_has_many.rb
- lib/api_maker/preloader_has_one.rb
- spec/api_maker/collection_serializer_spec.rb
> Fixed double preload included relationships

- lib/api_maker/preloader.rb
- lib/api_maker/serializer.rb
- spec/api_maker/collection_serializer_spec.rb
Asana: https://app.asana.com/0/741415267509551/943336150734608
> Preloader: Fixed wrong empty relationships preloaded

- lib/api_maker/preloader_has_many.rb
- spec/api_maker/preloading/has_many_through_belongs_to_spec.rb
Asana: https://app.asana.com/0/692848818155199/1113289352475565
> Fixed relationships loaded too many times issue

- lib/api_maker.rb
- lib/api_maker/railtie.rb
Asana: https://app.asana.com/0/919177422484240/1108582279746369
> Reload routes if routes.json changes

- lib/api_maker.rb
- lib/api_maker/individual_command.rb
- lib/api_maker/railtie.rb
- lib/api_maker/result_parser.rb
Asana: https://app.asana.com/0/741415267509551/1112160808790896
> Parse results to optimise output

- lib/api_maker/javascript/session-status-updater.js
Asana: https://app.asana.com/0/741415267509551/1115502830975276
> Check session status after online event

- lib/api_maker/spec_helper.rb
Added new helper to SpecHelper: wait_for_selectors in order to simplify code
> SpecHelper: wait_for_selectors

- app/services/api_maker/create_command.rb
- spec/api_maker/collection_serializer_spec.rb
- spec/dummy/app/api_maker/resources/application_resource.rb
- spec/dummy/app/api_maker/resources/project_resource.rb
- spec/dummy/app/javascript/api-maker/bootstrap/attribute-rows.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/card.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/select.jsx
- spec/dummy/app/javascript/api-maker/cable-subscription-pool.js
- spec/dummy/app/javascript/api-maker/commands-pool.js
- spec/system/models/create_spec.rb
- spec/system/models/destroy_spec.rb
- spec/system/models/find_spec.rb
- spec/system/models/has_one_spec.rb
- spec/system/models/update_spec.rb
https://app.asana.com/0/949322015222307/1135155266936519
> Models: Check access before create

- lib/api_maker/base_resource.rb
- lib/api_maker/javascript/sort-link.jsx
- lib/api_maker/model_extensions.rb
- lib/api_maker/serializer.rb
- spec/api_maker/base_resource_spec.rb
- spec/api_maker/serializer_spec.rb
- spec/dummy/app/api_maker/resources/account_resource.rb
- spec/dummy/app/javascript/api-maker/bootstrap/checkboxes.jsx
- spec/dummy/app/javascript/api-maker/models/account.js
- spec/dummy/app/javascript/api-maker/sort-link.jsx
- spec/dummy/app/models/account.rb
https://app.asana.com/0/1134627839222760/1141473707937491
> Default selected attributes

- app/services/api_maker/models_generator_service.rb
- lib/api_maker/javascript/bootstrap/live-table.jsx
- lib/api_maker/javascript/key-value-store.js
- lib/api_maker/javascript/live-table/index.jsx
- lib/api_maker/javascript/params.js
https://app.asana.com/0/949322015222307/1146224837403369
> Live table

- lib/api_maker/memory_storage.rb
- spec/api_maker/memory_storage_spec.rb
- spec/dummy/app/javascript/api-maker/bootstrap/string-input.jsx
https://app.asana.com/0/1134627839222760/1141082114888171
> Fixed resource_for_model with custom model_class

- .rubocop.yml
- app/channels/api_maker/subscriptions_channel.rb
- app/services/api_maker/command_response.rb
- lib/api_maker/model_extensions.rb
- spec/api_maker/model_extensions_spec.rb
- spec/dummy/app/javascript/api-maker/bootstrap/card.jsx
- spec/dummy/config/initializers/api_maker.rb
- spec/factories/activities.rb
https://app.asana.com/0/1134627839222760/1141082114888171
> Fixed wrong channel names for resources with custom model class

- app/controllers/api_maker/commands_controller.rb
- app/services/api_maker/collection_command_service.rb
- app/services/api_maker/command_service.rb
- app/services/api_maker/create_command_service.rb
- app/services/api_maker/destroy_command_service.rb
- app/services/api_maker/index_command_service.rb
- app/services/api_maker/member_command_service.rb
- app/services/api_maker/update_command_service.rb
- app/services/api_maker/valid_command_service.rb
- lib/api_maker/javascript/base-model.js
- lib/api_maker/javascript/collection.js
- lib/api_maker/javascript/commands-pool.js
- lib/api_maker/javascript/model-template.js.erb
- spec/api_maker/collection_command_service_spec.rb
- spec/api_maker/update_command_service_spec.rb
- spec/dummy/app/javascript/api-maker/base-model.js
- spec/dummy/app/javascript/api-maker/collection.js
- spec/dummy/app/javascript/api-maker/commands-pool.js
- spec/dummy/app/javascript/api-maker/models/task.js
https://app.asana.com/0/1134627839222760/1145142353768817
> Fixed correct model class and resource for resources with custom model class

- app/services/api_maker/validation_errors_generator_service.rb
- lib/api_maker/javascript/bootstrap/select.jsx
- lib/api_maker/javascript/bootstrap/string-input.jsx
- lib/api_maker/javascript/validation-errors.js
- spec/api_maker/update_command_spec.rb
- spec/dummy/app/api_maker/resources/project_resource.rb
- spec/dummy/app/api_maker/resources/user_resource.rb
- spec/dummy/app/javascript/api-maker/bootstrap/select.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/string-input.jsx
- spec/dummy/app/javascript/api-maker/models/project.js
- spec/dummy/app/javascript/api-maker/validation-errors.js
- spec/dummy/app/javascript/components/models/validation-errors.jsx
- spec/dummy/app/javascript/controllers/models/create_controller.js
- spec/dummy/app/models/project.rb
- spec/dummy/app/models/task.rb
- spec/factories/projects.rb
- spec/system/models/create_spec.rb
- spec/system/models/validation_errors_spec.rb
https://app.asana.com/0/1153435032856801/1154510136427385
> Validation errors: Match on input name instead of unique key

- lib/api_maker/javascript/base-model.js
- lib/api_maker/javascript/form-data-to-object.js
- spec/dummy/app/javascript/api-maker/base-model.js
- spec/dummy/app/javascript/api-maker/form-data-to-object.js
- spec/dummy/app/javascript/components/bootstrap/checkbox-boolean.jsx
- spec/dummy/app/javascript/components/bootstrap/checkboxes.jsx
- spec/dummy/app/javascript/components/bootstrap/string-input-date.jsx
- spec/dummy/app/javascript/components/bootstrap/string-input-datetime-local.jsx
- spec/dummy/app/javascript/components/bootstrap/string-input-file.jsx
- spec/dummy/app/javascript/components/models/validation-errors.jsx
https://app.asana.com/0/1153435032856801/1154591174053995
> Validation errors: Simplified by only needing to pass form

- lib/api_maker/javascript/bootstrap/checkbox.jsx
- lib/api_maker/javascript/bootstrap/checkboxes.jsx
- lib/api_maker/javascript/bootstrap/radio-buttons.jsx
- lib/api_maker/javascript/bootstrap/select.jsx
- lib/api_maker/javascript/bootstrap/string-input.jsx
- lib/api_maker/javascript/errors.js
- lib/api_maker/javascript/validation-errors.js
- spec/dummy/app/javascript/api-maker/bootstrap/checkbox.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/checkboxes.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/radio-buttons.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/select.jsx
- spec/dummy/app/javascript/api-maker/bootstrap/string-input.jsx
- spec/dummy/app/javascript/api-maker/errors.js
- spec/dummy/app/javascript/api-maker/validation-errors.js
https://app.asana.com/0/1153435032856801/1153508350476932
> Validation errors: Fixed various issues

- lib/api_maker/javascript/error-logger.js
- spec/dummy/app/javascript/api-maker/error-logger.js
https://app.asana.com/0/1155707064959056/1155707320173472
> Error logger: First resolve when Retrace has returned

- app/services/api_maker/models_generator_service.rb
- lib/api_maker/javascript/error-logger.js
- lib/api_maker/javascript/source-maps-loader.js
- spec/dummy/app/javascript/api-maker/error-logger.js
- spec/dummy/app/javascript/api-maker/source-maps-loader.js
- spec/dummy/app/javascript/shared/error-logger.js
- spec/dummy/app/javascript/shared/react-app.jsx
- spec/dummy/package.json
- spec/dummy/yarn.lock
- spec/system/models/created_event_spec.rb
https://app.asana.com/0/1153435032856801/1164854530857492
> Parse stack traces

- app/services/api_maker/index_command.rb
- lib/api_maker/javascript/result.js
- spec/dummy/app/javascript/api-maker/result.js
- spec/rails_helper.rb
- spec/system/models/create_spec.rb
https://app.asana.com/0/1153435032856801/1165943854543785
> Collections: Added per page in meta data

- Gemfile.lock
- api_maker.gemspec
- app/services/api_maker/destroy_command.rb
- lib/api_maker/individual_command.rb
- spec/api_maker/destroy_command_spec.rb
- spec/dummy/app/javascript/api-maker/base-model.js
- spec/dummy/app/javascript/api-maker/cable-connection-pool.js
- spec/dummy/app/javascript/api-maker/cable-subscription-pool.js
- spec/dummy/app/models/project.rb
- spec/rails_helper.rb
https://app.asana.com/0/1153435032856801/1170202844445756
> AIP destroy: Dependent restrict error messages

- npm-api-maker-bootstrap/index.js
- npm-api-maker-bootstrap/src/index.js
- npm-api-maker-bootstrap/src/live-table.jsx
- peak_flow.yml
- ruby-gem/lib/api_maker/javascript/cable-subscription-pool.js
- ruby-gem/spec/dummy/app/assets/javascripts/cable.js
- ruby-gem/spec/dummy/app/assets/javascripts/react.js.erb
- ruby-gem/spec/dummy/app/javascript/api-maker/cable-subscription-pool.js
- ruby-gem/spec/dummy/app/javascript/channels/consumer.js
- ruby-gem/spec/dummy/package.json
- ruby-gem/spec/dummy/yarn.lock
https://app.asana.com/0/1174912290170505/1181530512547511
> LiveTable revival and ActionCable through Webpack

- npm-api-maker-bootstrap/package.json
- npm-api-maker-bootstrap/src/live-table.jsx
https://app.asana.com/0/1174912290170505/1181530512547515
> Live table: onModelsLoaded prop

- ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
- ruby-gem/spec/api_maker/validation_errors_generator_service_spec.rb
https://app.asana.com/0/1153435032856801/1185219831465947
> Validation errors array support

- ruby-gem/app/services/api_maker/abilities_loader.rb
- ruby-gem/lib/api_maker/collection_serializer.rb
https://app.asana.com/0/1153435032856801/1186826115727233
> Abilities loader: Fixed loading abilities for other than primary model

- ruby-gem/lib/api_maker/javascript/deserializer.js
- ruby-gem/lib/api_maker/javascript/models-response-reader.js
- ruby-gem/lib/api_maker/javascript/preloaded.js
- ruby-gem/spec/dummy/app/javascript/api-maker/deserializer.js
- ruby-gem/spec/dummy/app/javascript/api-maker/models-response-reader.js
- ruby-gem/spec/dummy/app/javascript/api-maker/preloaded.js
https://app.asana.com/0/1153435032856801/1189209301559705
> Replace all dashes with underscores

- ruby-gem/lib/api_maker/javascript/deserializer.js
- ruby-gem/spec/dummy/app/javascript/api-maker/deserializer.js
https://app.asana.com/0/1153435032856801/1189835175200017
> Deserializer: Fixed not parsing sub models data

- npm-api-maker/index.js
- npm-api-maker/src/can-can.js
- npm-api-maker/src/index.js
- npm-api-maker/src/serializer.js
- ruby-gem/app/api_maker/services/can_can/load_abilities.rb
- ruby-gem/app/services/api_maker/deserializer.rb
- ruby-gem/lib/api_maker/base_command.rb
- ruby-gem/lib/api_maker/javascript/commands-pool.js
- ruby-gem/lib/api_maker/result_parser.rb
https://app.asana.com/0/1153435032856801/1190539797520017
> CanCan: Load resource abilities

- npm-api-maker/package.json
- ruby-gem/lib/api_maker/spec_helper.rb
https://app.asana.com/0/1153435032856801/1190539797520017
> Fixed remembered logs

- npm-api-maker-inputs/src/checkbox.jsx
https://app.asana.com/0/1153435032856801/1190982789461901
> Removed Bootstrap class name from checkbox

- ruby-gem/lib/api_maker/javascript/preloaded.js
- ruby-gem/spec/dummy/app/javascript/api-maker/preloaded.js
https://app.asana.com/0/1153435032856801/1192443197554159
> Preloaded performance optimisation

- ruby-gem/Gemfile.lock
- ruby-gem/api_maker.gemspec
- ruby-gem/app/services/api_maker/service_command.rb
https://app.asana.com/0/1153435032856801/1192443197554159
> Upgraded ServicePattern

- npm-api-maker-bootstrap/src/radio-buttons.jsx
https://app.asana.com/0/1153435032856801/1188418600796997
> Radio buttons: onChange support

- ruby-gem/lib/api_maker/permitted_params_argument.rb
- ruby-gem/spec/api_maker/permitted_params_argument_spec.rb
https://app.asana.com/0/1153435032856801/1194328617746937
> Permitted params argument: Always supply params even if none given

- npm-api-maker/index.js
- npm-api-maker/src/command-submit-data.js
- npm-api-maker/src/index.js
- ruby-gem/app/controllers/api_maker/commands_controller.rb
- ruby-gem/lib/api_maker/javascript/commands-pool.js
- ruby-gem/lib/api_maker/permitted_params_argument.rb
- ruby-gem/spec/api_maker/permitted_params_argument_spec.rb
https://app.asana.com/0/1153435032856801/1194328617746937
> Submit JSON instead of buggy form data

- npm-api-maker/src/event-connection.jsx
- npm-api-maker/src/event-updated.jsx
https://app.asana.com/0/1153435032856801/1194748007006200
> Events: Active prop

- npm-api-maker-bootstrap/package.json
- npm-api-maker-bootstrap/src/checkbox.jsx
- npm-api-maker-bootstrap/src/checkboxes.jsx
- npm-api-maker-bootstrap/src/input.jsx
- npm-api-maker-bootstrap/src/radio-buttons.jsx
- npm-api-maker-bootstrap/src/select.jsx
- ruby-gem/lib/api_maker/javascript/validation-errors.js
- ruby-gem/spec/dummy/app/javascript/api-maker/commands-pool.js
- ruby-gem/spec/dummy/app/javascript/api-maker/validation-errors.js
https://app.asana.com/0/1153435032856801/1196060573274509
> Match validation errors

- ruby-gem/app/services/api_maker/command_response.rb
- ruby-gem/lib/api_maker/base_command.rb
- ruby-gem/lib/api_maker/javascript/commands-pool.js
https://app.asana.com/0/1153435032856801/1198186330554739
> Bug report URL injection support

- npm-api-maker/src/api.js
https://app.asana.com/0/1153435032856801/1198490623631695
> Pass on XHR in custom errors

- npm-api-maker-inputs/src/id-for-component.js
https://app.asana.com/0/1153435032856801/1198298683672844
> Inputs: Always use given ID if given

- ruby-gem/lib/api_maker/javascript/base-model.js
- ruby-gem/lib/api_maker/javascript/model-template.js.erb
- ruby-gem/spec/dummy/app/javascript/api-maker/base-model.js
https://app.asana.com/0/1153435032856801/1198298683672844
> Read attributes with and without underscore

- ruby-gem/lib/api_maker/preloader_belongs_to.rb
- ruby-gem/spec/api_maker/preloader_belongs_to_spec.rb
- ruby-gem/spec/dummy/app/javascript/api-maker/resource-route.jsx
- ruby-gem/spec/system/models/belongs_to_spec.rb
https://app.asana.com/0/1153435032856801/1198989064963040
> Preloader belongs to: Fixed "WHERE id IS NULL" queries

- npm-api-maker/src/api.js
https://app.asana.com/0/1153435032856801/1198490623631695
> Set Peakflow variables for better error reports

- ruby-gem/lib/api_maker/preloader_base.rb
https://app.asana.com/0/1153435032856801/1199146114420637
> Preloader base: Use "WHERE EXISTS (sub_query)" instead of "WHERE id IN (sub_query)" which is much faster

- npm-api-maker/src/errors.js
https://app.asana.com/0/1153435032856801/1199382215123733
> Fixed: Custom error: [Object, object]

- ruby-gem/lib/api_maker/preloader_base.rb
- ruby-gem/spec/api_maker/preloading/has_many_polymorphic_spec.rb
- ruby-gem/spec/api_maker/preloading/has_many_spec.rb
- ruby-gem/spec/dummy/app/api_maker/resources/task_resource.rb
- ruby-gem/spec/dummy/app/javascript/api-maker/commands-pool.js
- ruby-gem/spec/dummy/app/javascript/shared/display-notification.js
- ruby-gem/spec/dummy/app/models/account.rb
- ruby-gem/spec/dummy/db/migrate/20201128105835_add_admin_to_users.rb
- ruby-gem/spec/dummy/db/schema.rb
- ruby-gem/spec/system/models/paginate_spec.rb
https://app.asana.com/0/1153435032856801/1199382215123736
> Skip unnecessary large ability SQL if unconditioned read access

- ruby-gem/spec/dummy/config/webpack/environment.js
Takes Webpack compilation down from ~1m to ~10s.
> Cache Webpack Babel

- npm-api-maker/src/base-model.js
- ruby-gem/app/api_maker/services/models/find_or_create_by.rb
- ruby-gem/app/services/api_maker/create_command.rb
https://app.asana.com/0/1153435032856801/1199711436008016
> Find or create by

- npm-api-maker/src/resource-route.jsx
- ruby-gem/lib/api_maker/resource_routing.rb
https://app.asana.com/0/1153435032856801/1199726372500787
> Require using different layouts

- npm-api-maker/src/base-model.js
https://app.asana.com/0/1153435032856801/1199668715963085
> Only refresh data after updating

- ruby-gem/lib/api_maker/individual_command.rb
- ruby-gem/spec/api_maker/individual_command_spec.rb
https://app.asana.com/0/1153435032856801/1199905919038153
> Fixed command name not in error message

- npm-api-maker/__tests__/collection.test.js
- npm-api-maker/package.json
- npm-api-maker/src/base-model.cjs
- npm-api-maker/src/collection.cjs
- npm-api-maker/src/merge.cjs
- npm-api-maker/src/params.cjs
- npm-api-maker/yarn.lock
https://app.asana.com/0/1153435032856801/1199919361318891
> Collection: Fixed recursive merge issue

- ruby-gem/app/services/api_maker/select_columns_on_collection.rb
- ruby-gem/lib/api_maker/base_resource.rb
- ruby-gem/lib/api_maker/collection_serializer.rb
- ruby-gem/lib/api_maker/preloader_base.rb
- ruby-gem/lib/api_maker/preloader_belongs_to.rb
- ruby-gem/lib/api_maker/preloader_has_many.rb
- ruby-gem/lib/api_maker/preloader_has_one.rb
- ruby-gem/spec/api_maker/collection_serializer_spec.rb
- ruby-gem/spec/dummy/app/api_maker/resources/user_resource.rb
- ruby-gem/spec/dummy/app/models/user.rb
- ruby-gem/spec/dummy/db/migrate/20210211124303_add_first_name_and_last_name_to_users.rb
- ruby-gem/spec/dummy/db/schema.rb
https://app.asana.com/0/1153435032856801/1199919361318891
> Attributes require columns

- ruby-gem/app/services/api_maker/select_columns_on_collection.rb
- ruby-gem/lib/api_maker/base_resource.rb
- ruby-gem/spec/api_maker/collection_serializer_spec.rb
- ruby-gem/spec/api_maker/serializer_spec.rb
- ruby-gem/spec/dummy/app/api_maker/resources/activity_resource.rb
- ruby-gem/spec/dummy/app/api_maker/resources/user_resource.rb
https://app.asana.com/0/1153435032856801/1199919361318891
> Automatically select simple attributes mapped to columns

- ruby-gem/lib/api_maker/spec_helper.rb
- ruby-gem/lib/api_maker/spec_helper/execute_collection_command.rb
- ruby-gem/spec/services/api_maker/base_command_spec.rb
https://app.asana.com/0/1153435032856801/1200041605970425
> Execute collection command

- ruby-gem/lib/api_maker/spec_helper/execute_collection_command.rb
- ruby-gem/lib/api_maker/spec_helper/execute_member_command.rb
- ruby-gem/spec/dummy/app/api_maker/commands/tasks/test_collection.rb
- ruby-gem/spec/dummy/app/api_maker/commands/tasks/test_member.rb
- ruby-gem/spec/services/api_maker/base_command_spec.rb
https://app.asana.com/0/1153435032856801/1200041605970427
> Use passed api maker args

- npm-api-maker/src/routes.cjs
- ruby-gem/README.md
- ruby-gem/app/services/api_maker/routes_file_reloader.rb
- ruby-gem/lib/api_maker/configuration.rb
- ruby-gem/lib/api_maker/railtie.rb
- ruby-gem/spec/dummy/config/initializers/js_routes.rb
https://app.asana.com/0/1153435032856801/1200058209672578
> Dynamic route definitions reloading

- npm-api-maker/__tests__/cable-connection-pool.test.js
- npm-api-maker/__tests__/cable-subscription-pool.test.js
- npm-api-maker/src/cable-connection-pool.cjs
- npm-api-maker/src/cable-subscription-pool.cjs
https://app.asana.com/0/1153435032856801/1200060736285173
> Fixed connecting to unsubscribed events

- ruby-gem/lib/api_maker/base_resource.rb
- ruby-gem/spec/api_maker/preloading/has_many_spec.rb
- ruby-gem/spec/dummy/app/api_maker/resources/account_marked_task_resource.rb
- ruby-gem/spec/dummy/app/api_maker/resources/task_detail_resource.rb
- ruby-gem/spec/dummy/app/api_maker/resources/task_resource.rb
- ruby-gem/spec/resources/task_detail_resource_spec.rb
- ruby-gem/spec/resources/task_resource_spec.rb
https://app.asana.com/0/1153435032856801/1200004503537768
> Can access through: Support for SQL rules

- ruby-gem/Gemfile.lock
- ruby-gem/api_maker.gemspec
- ruby-gem/lib/api_maker.rb
- ruby-gem/lib/api_maker/collection_serializer.rb
- ruby-gem/lib/api_maker/serializer.rb
- ruby-gem/spec/api_maker/destroy_command_spec.rb
- ruby-gem/spec/dummy/app/models/project_secret.rb
- ruby-gem/spec/factories/project_secrets.rb
https://app.asana.com/0/1153435032856801/1200088884488611
> Fixed missing require active record better dependent error messages

- npm-api-maker/__tests__/collection.test.js
- npm-api-maker/src/collection.cjs
https://app.asana.com/0/1153435032856801/1200090003314498
> Collection: Fixed Ransack cleared if given undefined

- npm-api-maker/index.js
- npm-api-maker/package.json
- npm-api-maker/src/collection.cjs
- npm-api-maker/src/instance-of-class-name.cjs
- npm-api-maker/src/result.cjs
- ruby-gem/spec/system/bootstrap/attribute_rows_spec.rb
https://app.asana.com/0/1153435032856801/1200090003314498
> Fixed dynamic prop type errors

- npm-api-maker-bootstrap/package.json
- npm-api-maker-bootstrap/src/live-table.jsx
- npm-api-maker-bootstrap/src/paginate.jsx
- npm-api-maker-bootstrap/yarn.lock
- npm-api-maker/package.json
https://app.asana.com/0/1153435032856801/1200090003314498
> Live table and paginate/use instance of class name

- npm-api-maker/src/devise.cjs
- npm-api-maker/src/session-status-updater.cjs
https://app.asana.com/0/1153435032856801/1200058209672589
> Session status updater: Use async/await

- npm-api-maker/package.json
- npm-api-maker/src/devise.cjs
https://app.asana.com/0/1153435032856801/board
> Devise: Allow more event listeners

- npm-api-maker/src/cable-connection-pool.cjs
- ruby-gem/Gemfile.lock
https://app.asana.com/0/1153435032856801/1200099706489042
> Cable connections: Removed delay

- ruby-gem/lib/api_maker/preloader.rb
- ruby-gem/lib/api_maker/preloader_has_many.rb
- ruby-gem/spec/api_maker/preloading/has_many_spec.rb
https://app.asana.com/0/1153435032856801/1200058209672629
> Fixed has_many double preloading same relationship with different path

- ruby-gem/app/services/api_maker/base_command.rb
- ruby-gem/app/services/api_maker/command_failed_error.rb
- ruby-gem/lib/api_maker/command_spec_helper.rb
- ruby-gem/spec/api_maker/service_command_spec.rb
https://app.asana.com/0/1153435032856801/1200210232682955
> Command fail with real error

- npm-api-maker-inputs/src/input.jsx
https://app.asana.com/0/1153435032856801/1200229584477350
> Input: Localized number support

- npm-api-maker/src/commands-pool.cjs
- ruby-gem/lib/api_maker/spec_helper.rb
- ruby-gem/lib/api_maker/spec_helper/wait_for_api_maker_to_finish.rb
- ruby-gem/spec/rails_helper.rb
https://app.asana.com/0/1153435032856801/1200322683113655
> Wait for API maker to finish in tests

- ruby-gem/app/services/api_maker/select_parser.rb
- ruby-gem/lib/api_maker/base_resource.rb
- ruby-gem/spec/services/api_maker/select_parser_spec.rb
https://app.asana.com/0/1153435032856801/1200334381927429
> Raise error when selecting an invalid attribute

- npm-api-maker/__tests__/base-model.test.js
- npm-api-maker/src/base-model.cjs
https://app.asana.com/0/1153435032856801/1200337248894242
> Parse validation errors optional throw

- npm-api-maker-bootstrap/src/checkbox.jsx
- npm-api-maker-bootstrap/src/invalid-feedback.jsx
- npm-api-maker-inputs/src/checkbox.jsx
- ruby-gem/spec/dummy/app/api_maker/resources/project_resource.rb
- ruby-gem/spec/dummy/app/api_maker/resources/user_resource.rb
- ruby-gem/spec/dummy/app/javascript/routes/models/validation-errors.jsx
- ruby-gem/spec/dummy/app/models/project.rb
- ruby-gem/spec/dummy/config/locales/en.yml
- ruby-gem/spec/dummy/db/migrate/20210516165612_add_illegal_to_projects.rb
- ruby-gem/spec/dummy/db/schema.rb
- ruby-gem/spec/system/models/validation_errors_spec.rb
https://app.asana.com/0/1153435032856801/1200337248894244
> Checkbox validation errors

- ruby-gem/app/services/api_maker/base_command.rb
- ruby-gem/app/services/api_maker/models/save.rb
- ruby-gem/app/services/api_maker/simple_model_errors.rb
- ruby-gem/spec/api_maker/simple_model_errors_spec.rb
- ruby-gem/spec/dummy/app/api_maker/commands/tasks/failure_save_response.rb
- ruby-gem/spec/services/api_maker/base_command_spec.rb
https://app.asana.com/0/1153435032856801/1200337715691858
> Made failure save response support simple model errors

- npm-api-maker/__tests__/base-model.test.js
- npm-api-maker/src/base-model.cjs
https://app.asana.com/0/1153435032856801/1200339361050223
> Parse validation errors should handle empty options

- npm-api-maker-inputs/src/checkbox.jsx
- ruby-gem/spec/dummy/app/javascript/routes/models/validation-errors.jsx
- ruby-gem/spec/dummy/package.json
- ruby-gem/spec/dummy/yarn.lock
https://app.asana.com/0/1153435032856801/1200340238192106
> Checkbox input ref

- ruby-gem/app/services/api_maker/validation_errors_generator_service.rb
- ruby-gem/spec/api_maker/validation_errors_generator_service_spec.rb
- ruby-gem/spec/dummy/app/models/user.rb
https://app.asana.com/0/1153435032856801/1200343177746821
> Whitelist additional attributes for validation errors

- ruby-gem/app/services/api_maker/base_command.rb
- ruby-gem/app/services/api_maker/simple_model_errors.rb
- ruby-gem/spec/dummy/app/api_maker/commands/users/failure_save_response.rb
- ruby-gem/spec/services/api_maker/base_command_spec.rb
https://app.asana.com/0/1153435032856801/1200384164314347
> Made failure save response support additional attributes

- npm-api-maker/package.json
- npm-api-maker/src/cable-subscription-pool.cjs
- ruby-gem/spec/dummy/app/api_maker/resources/task_resource.rb
- ruby-gem/spec/dummy/app/javascript/routes/models/model-class-event.jsx
- ruby-gem/spec/dummy/app/javascript/shared/route-definitions.json
- ruby-gem/spec/system/models/model_class_event_spec.rb
https://app.asana.com/0/1153435032856801/1200402879529734
> Fixed crash on model class events where model instance is null

- npm-api-maker/__tests__/can-can.test.js
- npm-api-maker/package.json
- npm-api-maker/src/can-can.cjs
- npm-api-maker/yarn.lock
- ruby-gem/spec/dummy/app/javascript/components/can-can/loader-that-signs-out-on-mount.jsx
- ruby-gem/spec/dummy/app/javascript/components/can-can/loader-with-state.jsx
- ruby-gem/spec/dummy/app/javascript/routes/can-can/loader.jsx
- ruby-gem/spec/dummy/config/webpack/environment.js
- ruby-gem/spec/system/can_can/loader_spec.rb
https://app.asana.com/0/1153435032856801/1200414246236228
> Use epic lock

- ruby-gem/app/services/api_maker/base_command.rb
https://app.asana.com/0/1153435032856801/1200422015139704
> Implemented inspect for base command

- npm-api-maker-bootstrap/src/input.jsx
- ruby-gem/spec/dummy/app/javascript/routes/bootstrap/string-input.jsx
- ruby-gem/spec/dummy/app/javascript/shared/route-definitions.json
- ruby-gem/spec/dummy/package.json
- ruby-gem/spec/dummy/yarn.lock
- ruby-gem/spec/system/bootstrap/string_input_spec.rb
https://app.asana.com/0/1153435032856801/1200498967566424
> Added option to append and prepend without text wrapper

- npm-api-maker/package.json
- npm-api-maker/src/base-model.cjs
https://app.asana.com/0/1153435032856801/1200675162594138
> Base model cache key: Handle updated at not date

- npm-api-maker/src/deserializer.cjs
- npm-api-maker/src/devise.cjs
- ruby-gem/app/views/api_maker/_data.html.erb
- ruby-gem/lib/api_maker/serializer.rb
- ruby-gem/spec/system/bootstrap/string_input_spec.rb
https://app.asana.com/0/1153435032856801/1200675162594138
> Devise: Fixed unnecessary JSON parsing

- ruby-gem/app/controllers/api_maker/commands_controller.rb
- ruby-gem/app/services/api_maker/deep_merge_params.rb
- ruby-gem/spec/services/api_maker/deep_merge_params_spec.rb
https://app.asana.com/0/1153435032856801/1200782986832623
> Deep merge arrays in commands controller

- ruby-gem/app/channels/api_maker/subscriptions_channel.rb
- ruby-gem/app/services/api_maker/collection_loader.rb
https://app.asana.com/0/1153435032856801/1200817995513044
> CollectionLoader: Fixed performance issue by removing group by and added more logging

- npm-api-maker/__tests__/model-prop-type.test.js
- npm-api-maker/__tests__/support/task.js
- npm-api-maker/index.js
- npm-api-maker/src/model-prop-type.cjs
https://app.asana.com/0/1153435032856801/1200956876552466
> ModelPropType class to validate required attributes

- npm-api-maker/__tests__/model-prop-type.test.js
- npm-api-maker/__tests__/support/task.js
- npm-api-maker/__tests__/support/user.js
- npm-api-maker/src/model-prop-type.cjs
https://app.asana.com/0/1153435032856801/1200956876552466
> ModelPropType: withAttributes ignore if new model

- npm-api-maker/src/model-prop-type.cjs
https://app.asana.com/0/1153435032856801/1200956876552466
> ModelPropType: Validate all preloaded sub models

- npm-api-maker/__tests__/base-model.test.js
- npm-api-maker/__tests__/support/user.js
- npm-api-maker/src/base-model.cjs
- npm-api-maker/src/event-connection.jsx
- npm-api-maker/src/event-created.jsx
- npm-api-maker/src/event-destroyed.jsx
- npm-api-maker/src/event-model-class.jsx
- npm-api-maker/src/event-updated.jsx
- npm-api-maker/src/model-events.cjs
- npm-api-maker/src/updated-attribute.jsx
https://app.asana.com/0/1153435032856801/1201060094607415
> BaseModel: identifierKey method

- api_maker_table_npm/src/column-visible.js
- api_maker_table_npm/src/model-row.jsx
- api_maker_table_npm/src/table-settings.js
- api_maker_table_npm/src/table.jsx
- api_maker_table_rubygem/app/models/api_maker_table/table_setting.rb
- peak_flow.yml
- ruby-gem/Gemfile
- ruby-gem/Gemfile.peakflow
- ruby-gem/gemfiles/kaminari.gemfile
- ruby-gem/gemfiles/kaminari.gemfile.lock
- ruby-gem/gemfiles/will_paginate.gemfile
- ruby-gem/gemfiles/will_paginate.gemfile.lock
- ruby-gem/spec/dummy/app/javascript/routes/bootstrap/live-table.jsx
- ruby-gem/spec/system/api_maker_table/api_maker_table_spec.rb
https://app.asana.com/0/1201894571418657/1202382291372473
https://tasks.kaspernj.org/tasks/6235
> Fixed default visible null shown

- api_maker_table_npm/package.json
- api_maker_table_npm/src/column-visible.js
- api_maker_table_npm/src/model-row.jsx
- api_maker_table_npm/src/table.jsx
- ruby-gem/Gemfile
- ruby-gem/Gemfile.lock
- ruby-gem/gemfiles/kaminari.gemfile
- ruby-gem/gemfiles/kaminari.gemfile.lock
- ruby-gem/gemfiles/will_paginate.gemfile
- ruby-gem/gemfiles/will_paginate.gemfile.lock
- ruby-gem/spec/system/api_maker_table/api_maker_table_spec.rb
https://app.asana.com/0/1201894571418657/1202034564300835
https://tasks.kaspernj.org/tasks/6126
> Only use default visible if present and otherwise true

- api_maker_table_npm/src/table.jsx
- npm-api-maker/src/collection-loader.jsx
https://app.asana.com/0/1201894571418657/1202486841741224
https://tasks.kaspernj.org/tasks/6318
> Table: Default group by ID

- api_maker_table_npm/src/model-row.jsx
- api_maker_table_npm/src/style.scss
- api_maker_table_npm/src/table.jsx
- api_maker_table_npm/src/variables.scss
- api_maker_table_npm/src/with-breakpoint.jsx
- npm-api-maker/src/config.js
- ruby-gem/spec/system/api_maker_table/api_maker_table_spec.rb
https://app.asana.com/0/1201894571418657/1202049966079708
https://tasks.kaspernj.org/tasks/6223
> Table: Responsive divs on small screens

- npm-api-maker/src/model-load-wrapper.jsx
- ruby-gem/app/services/api_maker/deserializer.rb
- ruby-gem/lib/api_maker/collection.rb
https://app.asana.com/0/1202408309966272/1202678089440482
https://tasks.kaspernj.org/tasks/6431
> Reload model if model ID changed

- npm-api-maker/src/base-model.mjs
- npm-api-maker/src/super-admin/config-reader.jsx
- npm-api-maker/src/super-admin/index-page/index.jsx
- npm-api-maker/src/super-admin/index.jsx
- npm-api-maker/src/super-admin/layout/index.jsx
- npm-api-maker/src/super-admin/layout/menu/menu-content.jsx
- npm-api-maker/src/super-admin/layout/no-access.jsx
- npm-api-maker/src/super-admin/models.js
- npm-api-maker/src/table/select-calculator.mjs
- ruby-gem/app/services/api_maker/model_content_generator_service.rb
https://app.asana.com/0/1202408309966272/1202921772144563
https://tasks.kaspernj.org/tasks/6629
> Super admin: Support for custom configs

- npm-api-maker/package.json
- npm-api-maker/src/bootstrap/attribute-row/index.jsx
- npm-api-maker/src/model-load-wrapper.jsx
- npm-api-maker/src/super-admin/config-reader.jsx
- npm-api-maker/src/super-admin/show-page.jsx
- ruby-gem/spec/system/super_admin/show_spec.rb
https://app.asana.com/0/1202408309966272/1202921772144558
> Super admin / Show page: Show attribute rows

- npm-api-maker/src/base-model.mjs
- npm-api-maker/src/collection-loader.jsx
- npm-api-maker/src/models.mjs.erb
- npm-api-maker/src/super-admin/index-page.jsx
- npm-api-maker/src/super-admin/index.jsx
- npm-api-maker/src/super-admin/model-class-table.jsx
- npm-api-maker/src/super-admin/show-nav.jsx
- npm-api-maker/src/super-admin/show-page.jsx
- npm-api-maker/src/super-admin/show-reflection-page.jsx
- npm-api-maker/src/table/table.jsx
https://app.asana.com/0/1202408309966272/1202867622541389
https://tasks.kaspernj.org/tasks/6615
> Super admin: Reflections on show page

- npm-api-maker/package.json
- npm-api-maker/src/bootstrap/card.jsx
- npm-api-maker/src/collection.mjs
- npm-api-maker/src/super-admin/index.jsx
- npm-api-maker/src/table/table.jsx
- npm-api-maker/yarn.lock
https://app.asana.com/0/1202408309966272/1202818985093951
https://tasks.kaspernj.org/tasks/6654
> Table: Footer with counts

- npm-api-maker/src/params.mjs
- npm-api-maker/src/table/filters/filter-form.jsx
- npm-api-maker/src/table/filters/index.jsx
- npm-api-maker/src/table/table.jsx
- ruby-gem/app/services/api_maker/collection_loader.rb
- ruby-gem/spec/system/api_maker_table/api_maker_table_spec.rb
- ruby-gem/spec/system/api_maker_table/custom_filtering_spec.rb
- ruby-gem/spec/system/api_maker_table/filter_spec.rb
- ruby-gem/spec/system/api_maker_table/sorting_spec.rb
https://app.asana.com/0/1202408309966272/1203043080478511
https://tasks.kaspernj.org/tasks/6656
> Fixed filtering directly on model

- npm-api-maker/src/collection-loader.jsx
- npm-api-maker/src/table/table.jsx
- ruby-gem/spec/system/api_maker_table/per_page_spec.rb
https://app.asana.com/0/1202408309966272/1203043080478511
https://tasks.kaspernj.org/tasks/6656
> Table: Per page

- npm-api-maker/package.json
- npm-api-maker/src/table/filters/filter-form.jsx
- npm-api-maker/src/table/filters/index.jsx
- ruby-gem/spec/system/api_maker_table/filter_spec.rb
https://app.asana.com/0/1202408309966272/1202881888004267
https://tasks.kaspernj.org/tasks/6655
> Table  filters  remove filter

- api_maker_table_rubygem/app/api_maker/resources/table_setting_column_resource.rb
- api_maker_table_rubygem/app/api_maker/resources/table_setting_resource.rb
- api_maker_table_rubygem/app/models/api_maker_table/table_setting.rb
- npm-api-maker/src/serializer.mjs
- npm-api-maker/src/table/table-settings.js
- ruby-gem/spec/dummy/package.json
- ruby-gem/spec/dummy/yarn.lock
- ruby-gem/spec/system/api_maker_table/anonymous_access_spec.rb
https://app.asana.com/0/1201894571418657/1203114322109917
https://tasks.kaspernj.org/tasks/6681
> Table: Anonymous access

- npm-api-maker/package.json
- npm-api-maker/src/bootstrap/sort-link.jsx
- npm-api-maker/src/collection-loader.jsx
- npm-api-maker/src/table/filters/index.jsx
- npm-api-maker/src/table/table.jsx
- ruby-gem/spec/dummy/app/javascript/routes/bootstrap/sort-link.jsx
- ruby-gem/spec/system/api_maker_table/api_maker_table_spec.rb
- ruby-gem/spec/system/bootstrap/sort_link_spec.rb
https://app.asana.com/0/1201894571418657/1203115029319901
https://tasks.kaspernj.org/tasks/6684
> Collection loader  fixed refresh issues with blank

- npm-api-maker/package.json
- npm-api-maker/src/bootstrap/live-table.jsx
- npm-api-maker/src/collection-loader.jsx
- npm-api-maker/src/table/table.jsx
https://app.asana.com/0/1201894571418657/1204195387290021
https://tasks.kaspernj.org/tasks/7204
> Collection loader: Dont do pagination by default

- api_maker_table_rubygem/Gemfile.lock
- api_maker_table_rubygem/api_maker_table.gemspec
- api_maker_table_rubygem/app/api_maker/commands/workplaces/add_query.rb
- api_maker_table_rubygem/app/api_maker/commands/workplaces/query_links_status.rb
- api_maker_table_rubygem/app/api_maker/commands/workplaces/remove_query.rb
- api_maker_table_rubygem/app/api_maker/resources/workplace_resource.rb
- npm-api-maker/package.json
- npm-api-maker/src/collection.mjs
- npm-api-maker/src/model-recipes-model-loader.mjs
- npm-api-maker/src/table/worker-plugins-check-all-checkbox.jsx
- ruby-gem/app/services/api_maker/translated_collections.rb
https://app.asana.com/0/1201894571418657/1204549793762467
https://tasks.kaspernj.org/tasks/7369
> Table / Worker plugins: All check status and remove query

- npm-api-maker/src/table/table.jsx
- ruby-gem/app/services/api_maker/collection_loader.rb
- ruby-gem/app/services/api_maker/deserializer.rb
- ruby-gem/app/services/api_maker/search_to_ransack_params.rb
- ruby-gem/lib/api_maker.rb
- ruby-gem/lib/api_maker/collection.rb
https://app.asana.com/0/1201894571418657/1204587827355380
https://tasks.kaspernj.org/tasks/7376
> Ruby / Collection: Support search params

- npm-api-maker/src/table/filters/filter-form.jsx
- npm-api-maker/src/table/filters/index.jsx
- ruby-gem/app/services/api_maker/search_to_ransack_params.rb
https://app.asana.com/0/1201894571418657/1204526923651294
https://tasks.kaspernj.org/tasks/7413
> Table / Filters / Ransackable scopes filtering

- npm-api-maker/src/base-model.mjs
- peak_flow.yml
- ruby-gem/Gemfile.lock
- ruby-gem/api_maker.gemspec
https://app.asana.com/0/1202408309966272/1204963478321120
https://tasks.kaspernj.org/tasks/7511
> Base model: Mark for destruction

- npm-api-maker/package.json
- npm-api-maker/src/table/table-settings.js
- npm-api-maker/yarn.lock
- ruby-gem/gemfiles/will_paginate.gemfile.lock
https://app.asana.com/0/1201894571418657/1205538744928942
https://tasks.kaspernj.org/tasks/7528
> Table settings: Avoid unique identifier crash

- api_maker_table_rubygem/app/api_maker/resources/table_setting_column_resource.rb
- npm-api-maker/package.json
- npm-api-maker/src/table/model-row.jsx
- npm-api-maker/src/table/settings/index.jsx
- npm-api-maker/src/table/settings/style.scss
- npm-api-maker/src/table/table.jsx
- ruby-gem/spec/system/api_maker_table/settings_spec.rb
https://app.asana.com/0/1201894571418657/1205558345356371
https://tasks.kaspernj.org/tasks/7548
> Table: Trigger column visibility

- npm-api-maker/package.json
- npm-api-maker/src/devise.mjs
https://app.asana.com/0/1202408309966272/1205591350282294
https://tasks.kaspernj.org/tasks/7553
https://www.peakflow.io/en/projects/wooftech/bug-reports/d33fc210-0699-4e47-a13f-69b3feae35e8/instances/f796cf82-e209-4918-8000-f2c1c6851033
> Devise  update session  support null and args scope

- npm-api-maker/src/super-admin/index-page.jsx
- npm-api-maker/src/super-admin/index.jsx
- ruby-gem/Gemfile.lock
- ruby-gem/api_maker.gemspec
- ruby-gem/gemfiles/rails_6.gemfile.lock
- ruby-gem/gemfiles/rails_7.gemfile.lock
- ruby-gem/lib/api_maker/spec_helper/super_admin_helpers.rb
- ruby-gem/spec/rails_helper.rb
- ruby-gem/spec/system/super_admin/show_spec.rb
https://app.asana.com/0/1202408309966272/1206609996183279
https://tasks.kaspernj.org/tasks/7864
> Super admin: Fixed destroy from show page

- npm-api-maker/src/super-admin/edit-page.jsx
- npm-api-maker/src/super-admin/show-page/index.jsx
- ruby-gem/lib/api_maker/spec_helper/super_admin_helpers.rb
https://app.asana.com/0/1202408309966272/1206609996183279
https://tasks.kaspernj.org/tasks/7864
> Super admin: Custom content in show and edit

- npm-api-maker/src/base-model/reflection.mjs
- npm-api-maker/src/super-admin/edit-page.jsx
- npm-api-maker/src/super-admin/index.jsx
- npm-api-maker/src/super-admin/show-reflection-actions.jsx
- npm-api-maker/src/super-admin/show-reflection-page.jsx
https://app.asana.com/0/1202408309966272/1206619595852000
https://tasks.kaspernj.org/tasks/7886
> Super admin: Create action on show reflection pages

- npm-api-maker/src/can-can.mjs
- npm-api-maker/src/super-admin/index.jsx
- npm-api-maker/src/super-admin/layout/index.jsx
- npm-api-maker/src/super-admin/layout/menu/index.jsx
- npm-api-maker/src/super-admin/layout/menu/menu-content.jsx
- npm-api-maker/src/use-can-can.mjs
- ruby-gem/spec/system/super_admin/dashboard_spec.rb
https://app.asana.com/0/1202408309966272/1206718852414196
https://tasks.kaspernj.org/tasks/7893
> Super admin: Fixed access issues

- npm-api-maker/src/table/table.jsx
https://app.asana.com/0/1201894571418657/1206162948263149
https://tasks.kaspernj.org/tasks/8160
> Table: Fixed responsive issues

- npm-api-maker/src/base-model/attribute.mjs
- npm-api-maker/src/super-admin/config-reader.jsx
- ruby-gem/app/services/api_maker/model_content_generator_service.rb
https://app.asana.com/0/1202408309966272/1207839842282562
https://tasks.kaspernj.org/tasks/8251
> Super admin / Tables: Always include sortable name

- npm-api-maker/src/super-admin/config-reader.jsx
- npm-api-maker/src/super-admin/model-class-table.jsx
https://app.asana.com/0/1202408309966272/1207839842282562
https://tasks.kaspernj.org/tasks/8251
> Super admin / Tables: Fixed selected columns

- npm-api-maker/package.json
- npm-api-maker/src/route.jsx
- npm-api-maker/src/router.jsx
- npm-api-maker/yarn.lock
https://app.asana.com/0/1202408309966272/1207966395344808
https://tasks.kaspernj.org/tasks/8294
> Partial routing with route component

- ruby-gem/lib/api_maker/result_parser.rb
https://app.asana.com/0/1202408309966272/1208110286335116
https://tasks.kaspernj.org/tasks/8377
> ResultParser: Fixed crash when no resource for given model

- npm-api-maker/src/table/header-column.jsx
- npm-api-maker/src/table/model-column.jsx
- npm-api-maker/src/table/model-row.jsx
- npm-api-maker/src/table/settings/column-row.jsx
- npm-api-maker/src/table/table.jsx
- npm-api-maker/src/table/widths.mjs
https://app.asana.com/0/1201894571418657/1207412612849343
https://tasks.kaspernj.org/tasks/8231
> Table: Set initial width better

- npm-api-maker/src/use-input.mjs
https://app.asana.com/0/1202408309966272/1208562945230270
https://tasks.kaspernj.org/tasks/8505
> useInput: Forward 'value' prop

- npm-api-maker/src/modal.jsx
- npm-api-maker/src/table/settings/index.jsx
https://app.asana.com/0/1201894571418657/1208587935576218
https://tasks.kaspernj.org/tasks/8516
> Dismissable modal with dark background

- npm-api-maker/src/super-admin/edit-page/edit-attribute-content.jsx
- npm-api-maker/src/super-admin/edit-page/edit-attribute-input.jsx
- npm-api-maker/src/super-admin/edit-page/edit-attribute.jsx
https://app.asana.com/0/1202408309966272/1208782010816186
https://tasks.kaspernj.org/tasks/8595
> Super admin: Fixed value for custom content and correct margin between elements

- npm-api-maker/src/bootstrap/sort-link.jsx
- npm-api-maker/src/table/components/row.jsx
- npm-api-maker/src/table/header-column.jsx
- npm-api-maker/src/table/model-column.jsx
- npm-api-maker/src/table/table.jsx
- ruby-gem/spec/system/api_maker_table/sorting_spec.rb
https://app.asana.com/0/1201894571418657/1208724365997648
https://tasks.kaspernj.org/tasks/8606
> Table: Responsive optimisations for small screens

- npm-api-maker/src/table/filters/filter.jsx
- npm-api-maker/src/table/filters/index.jsx
- ruby-gem/spec/system/api_maker_table/filter_spec.rb
https://app.asana.com/0/1202408309966272/1208848481044454
https://tasks.kaspernj.org/tasks/8630
> Table / Filters: Fixed edit scope filter

- npm-api-maker/package.json
- npm-api-maker/src/inputs/checkbox.jsx
- npm-api-maker/src/use-can-can.mjs
- npm-api-maker/yarn.lock
https://app.asana.com/0/1201894571418657/1209024314912007
https://tasks.diestoeckels.de/tasks/8690
> Inputs  checkbox  fixed registered name

- npm-api-maker/package-lock.json
- npm-api-maker/package.json
- npm-api-maker/src/super-admin/index.jsx
- npm-api-maker/src/super-admin/show-nav.jsx
- npm-api-maker/src/super-admin/show-reflection-actions.jsx
- npm-api-maker/src/super-admin/show-reflection-page.jsx
- npm-api-maker/src/use-styles.js
- npm-api-maker/src/utils/default-style.jsx
https://app.asana.com/0/1202408309966272/1209411753455727
https://tasks.diestoeckels.de/tasks/8728
> Fixed default style crash undefined variable

- npm-api-maker/src/config.js
- npm-api-maker/src/use-input.js
https://app.asana.com/1/1202408244876571/project/1202408309966272/task/1209638816352399
https://tasks.diestoeckels.de/tasks/8784
> useInput: Only match validation error if input name present

- npm-api-maker/src/inputs/money.jsx
https://app.asana.com/1/1201716481060035/project/1201894571418657/task/1209934054007279
https://tasks.diestoeckels.de/tasks/8857
https://www.peakflow.io/en/projects/gratisbyggetilbud_rails/bug-reports/3419ffdb-a808-41d4-ad32-5871e601848c/instances/b3daa3cb-d76d-4186-a618-6f1b1cdf9b39
> Inputs / Money: Fixed crash if no ref
